name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt install sysstat
          sudo apt install bats
          sudo apt install jq

      - name: Run Tests
        run: bats ./server-stats.bats
